### ISSUE TITLE
Old version of application stays running after update

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1481]
I (on ~palfun-foslup) and others (like ~tonlur-sarret) are running into an issue where we have received the latest version of talk, but don't seem to be running it. We can see changed/added application logic in the hoon file (in both base and home), but talk acts as if that weren't there.

We've tried editing the file manually, to make it re-sync. And it does, but still doesn't seem to affect the running code.

May or may not be related to urbit/arvo#501.

**Comment by vvisigoth** [comment]
@jtobin @philipcmonk any insight into this?

**Comment by philipcmonk** [comment]
I haven't seen it in a few months, but I wouldn't be surprised if it's still lurking around somewhere.  I don't know what could cause that subscription to fall off.

**Comment by Fang-** [comment]
Perhaps useful, @matildepark had reported this to me previously, and I've now experienced it myself. This issue seems to occur alongside (or because of) a `crud`.

Consider this dojo output, while updating an app whose `+prep` contains a printf that always fires.

```
> |commit %home
>=
: /~zod/home/129/app/klat/hoon
worker_send_replace 219236 crud
> |commit %home
>=
: /~zod/home/130/app/klat/hoon
```

We'd expect to see the printf here after both edits, but we don't. It had been firing fine previously.  
Incidentally, the `crud` happened on/after the first `|commit` that resulted in successfully-compiling app code, after a long sequence of error-hunting commits.

**Comment by philipcmonk** [comment]
Behn eats %drip errors, which is almost certainly what is happening there.
I've fixed this on the philip/mall-real branch, but that won't land in this
breach.

I'm out for the rest of this week, but it would be easy to add a handler
for %wake in behn that actually printed an error if it exists.

**Comment by Fang-** [comment]
> Behn eats %drip errors, which is almost certainly what is happening there.

Can confirm:

```
> |commit %home
>=
: /~zod/home/61/app/stream/hoon
worker_send_replace 99410 crud
drip failed
nest-fail
/~zod/home/~2019.10.16..05.49.49..104e/sys/vane/gall:<[2.345 9].[2.345 51]>
/~zod/home/~2019.10.16..05.49.49..104e/sys/vane/gall:<[2.344 9].[2.345 51]>
/~zod/home/~2019.10.16..05.49.49..104e/sys/vane/gall:<[2.343 9].[2.345 51]>
/~zod/home/~2019.10.16..05.49.49..104e/sys/vane/gall:<[2.342 7].[2.371 27]>
/~zod/home/~2019.10.16..05.49.49..104e/sys/vane/gall:<[2.340 7].[2.371 27]>
/~zod/home/~2019.10.16..05.49.49..104e/sys/vane/gall:<[1.253 25].[1.253 50]>
::  big stack
/~zod/home/~2019.10.16..05.49.49..104e/sys/vane/gall:<[2.591 3].[2.599 10]>
[%gall-take-failed /sys/core/stream/~zod/home/~2019.10.19..11.10.20..1f72]
/~zod/home/~2019.10.16..05.49.49..104e/sys/vane/gall:<[2.590 3].[2.599 10]>
/~zod/home/~2019.10.16..05.49.49..104e/sys/vane/gall:<[2.588 3].[2.599 10]>
[%failed-slym-in %g]
[%swim-take-vane %g %made]
[%failed-swim %g %f [~ /sys/core/stream/~zod/home/~2019.10.19..11.10.20..1f72]]
[%failed-take %g]
[%lal %g %c]
[%lal %g %d]
[%lal %g %b]
[%lal %g %f]
%failed-jack
bail: exit
```

**Comment by Fang-** [comment]
This is still in! At least, the following pathway to get into the "app doesn't update" state still is:

1. Make change to app.hoon
2. Commit the change
3. During subsequent <behn> spinner (where app recompilation happens), hit ctrl-c
4. Further changes to app.hoon will no longer cause recompilation

**Comment by belisarius222** [comment]
I think Ford still doesn't handle %drip failures properly ...

—
~rovnys-ricfer
https://urbit.org

**Comment by Fang-** [comment]
fwiw, `:goad %go` manages to recompile the app _and_ kick all the relevant subscriptions here back into gear, resolving the issue. Not great, but at least a workaround.

**Comment by tacryt-socryp** [comment]
I strongly believe this issue has been resolved by Ford fusion. Let me know if I can close.
