### ISSUE TITLE
Missed the OTA Update

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#1605]
I have a ship that's on 0.8.1 but it still has the urbit-help blank screen of death problem when comets post, and every post has a sigil next to it instead of one per new poster. That makes me believe that it somehow missed the update, and I don't know how to get it. Is the update a one-time-only kind of thing and if your ship isn't booted you're SOL?

**Comment by joemfb** [comment]
These updates go out through the sponsorship hierarchy -- you should get yours from your sponsor as soon a) they have it and b) you're both online and not swamped with other processing. The update is not a time-bounded event that can be missed. We've observed some ships taking longer than expected to deliver updates this era, and had to intervene to get them unstuck. It's possible your sponsor is in just such a state.

One thing we should do is make it easier to track the status of an in-progress OTA update (maybe by publishing %clay desk hashes).

Finally, it's worth noting that updates are delivered over-the-air via the ames protocol, which is implemented in the Arvo vane `%ames`. The current implementation is showing its age in a number of ways, and has long been slated for replacement (although, to be fair, it's holding better this era than it has in the last couple). New-ames, codenamed `%alef`, is currently being tested.

**Comment by custom-jonathan** [comment]
Fortunately my main planet is in tip top shape and everything here is non-urgent.

Alef sounds badass.

**Comment by custom-jonathan** [comment]
Update: The planet that missed the update escaped its dark star, and currently resides under another star. When I tried to `|hi` the star, it started a crud scroll. But it also spit out this error:

![image](https://user-images.githubusercontent.com/51895363/62975024-0f167f00-bddf-11e9-8b0f-b14a8107fa54.png)

Any idea if the `life=[old=4 new=5]` piece is an issue?

**Comment by philipcmonk** [comment]
Indeed, that says that you're hearing a message on ~livpub's key revision 5, but the most recent keys you have are for revision 4.  Usually you get key updates from your parent, but if you stopped getting those, then you must be behind.  You can check what key revision you have for any ship with the dojo command:

```
.^(life %j /=life=/~livpub)
```

On my ship, this gives 5.  Can you verify that it also gives 5 for you?

The issue of not getting key updates about your sponsor is known and fixed in #1436, the Jael rewrite.  Unfortunately, this will not be deployed until next breach.  In the meantime, the following commands should switch you to talking directly to an ethereum node:

```
|start %eth-manage
:eth-manage %look-ethnode
```

This might take a while to get up to date.  @Fang- or @ixv may know shortcuts.

**Comment by custom-jonathan** [comment]
I'm getting a wicked case of crud scroll & ames lock, but ctl+z will work when it becomes unresponsive. In the window of starting it up again and before the scroll starts, I'll run both.

**Comment by custom-jonathan** [comment]
I got this: 

`> .^(life %j /=life=/~livpub)
4`

**Comment by philipcmonk** [comment]
That confirms that your local knowledge of ~livpub's key revision is 4 while the true one is 5, so you just need to get that update somehow.  I think that `%look-ethnode` command is your best bet.

**Comment by custom-jonathan** [comment]
You're right. Ran eth-manage and everything seems to be good on that front. I'm now seeing livpub as 5 so that's a step in the right direction.

I'm still unable to view urbit-help when there's a comet in there like was happening before the OTA update, but this is progress!

**Comment by philipcmonk** [comment]
Indeed!  Can you run `|syncs` and give the output?  That will print out your active syncs.  It might just be that your filesystem is still synced to your previous sponsor, and you need to change that to the new sponsor.

**Comment by ohAitch** [comment]
Is there any tracking of like, the average latency of key change updates as
they propagate through the network?

**Comment by ohAitch** [comment]
I guess 90%ile (95? 99?) is more relevant in this case

**Comment by philipcmonk** [comment]
That would be nice to know.  The Jael on mainnet is known to have issues with that, but the new Jael is the one you actually want to measure because the subscription logic is completely redone.

In this case, I assume the problem is simply that the update was supposed to come from his sponsor, but that's exactly the ship that stopped talking to him.  In new Jael, we use our sponsor for all updates about all other ships, but for our sponsor specifically, we use the an ethereum node.

**Comment by custom-jonathan** [comment]
`sync configured from %base on ~talleg-botsug to %kids
sync configured from %kids on ~livpub to %base
sync configured from %base on ~talleg-botsug to %home
> |syncs
>=`

**Comment by custom-jonathan** [comment]
`sync configured from %base on ~talleg-botsug to %kids
sync configured from %kids on ~livpub to %base
sync configured from %base on ~talleg-botsug to %home
> |syncs
>=`

**Comment by custom-jonathan** [comment]
```
sync configured from %base on ~talleg-botsug to %kids
sync configured from %kids on ~livpub to %base
sync configured from %base on ~talleg-botsug to %home
> |syncs
>=
```

**Comment by joemfb** [comment]
You escaped *from* `~livpub`? If so, you'll want to run

```
> |unsync %base ~livpub %kids
> |sync %base (sein:title our now our) %kids
```

to remove the old sync and establish a new one with your new sponsor.

**Comment by custom-jonathan** [comment]
I escaped from ~run & ~fiprun and was adopted by ~livpub. So I should run:

```
|unsync %base ~fiprun %kids
|sync %base (sein:title our now our) %kids
```

?

**Comment by joemfb** [comment]
No, `|sync` with your sponsor is already configured properly, per the output you posted above.

**Comment by philipcmonk** [comment]
You could try an explicit merge in case there was a transient problem. This
will obliterate any local file changes!

|sync %base (sein:title our now our) %kids, =gem %that

**Comment by philipcmonk** [comment]
I meant `|merge`, not `|sync`

**Comment by custom-jonathan** [comment]
I'll give it a go!

**Comment by custom-jonathan** [comment]
Didn't seem to do anything appreciable. Still having the same chat hiccups of comets causing blank pages and sigils next to every post instead of every new post.

**Comment by mikolajpp** [comment]
I am hitting this exact same issue which seems unrelated to #1644. 
My planet has been running for 3 days without receiving an update. None of the suggestions 
in this thread seem to work. 

I can `|hi` my sponsor, all syncs are set up correctly, manual `|merge` does not do anything.

**Comment by vvisigoth** [comment]
@philipcmonk is the right thing to do here to |cancel until the queue goes to 0 and then to try to manual merge?

**Comment by joemfb** [comment]
If @mikolajpp's planet is far enough behind, `|cancel` itself is probably in a broken state (it was fixed via OTA in this era). If that's the case, you'll probably need to manually `|mount %`, copy in the arvo from the latest tagged release, and `|commit %home`.

**Comment by philipcmonk** [comment]
Yes, |cancel is what you want.  Unfortunately, if there's a pending merge, then |mount and |commit are blocked as well.  So, if |cancel says something about "not implemented", then the only way to break out of this is to manually inject the clay reload event.  We're still shipping broken pills, so it's very important for the first OTA update to come through cleanly.

**Comment by joemfb** [comment]
Ah, that's right. Sorry for the misdirection, @mikolajpp. There's more info on injecting a reload event here: https://github.com/urbit/urbit/blob/master/pkg/arvo/gen/reload-event.hoon.

@philipcmonk, it looks like %clay from the latest tagged release should be safe to inject manually. Can you confirm?

**Comment by philipcmonk** [comment]
Yes, the latest tagged release of clay should work (not master).

Note that you should run the `.event/ovo +reload-event %c` command on a ship (eg a fakezod) that has the clay.hoon you want to load.  So don't run it on the ship that already has the old clay.hoon.

**Comment by custom-jonathan** [comment]
So weird. I could see the urbit help chat 2 days ago with ~talleg and now it's back to the same state that this issue caused. 

Here's what I ran from my ~minder-folden ship:

```
> .^(@uv %cz /=base=)
0vf.8nv9n.k0c2g.rhik2.erf4b.6fabj.p4t3n.s6u6p.kabeg.rtafq.qnhb2
```

And here's what I ran from ~talleg:

```
> .^(@uv %cz /=base=)
0v3.gh0e6.0arta.j6dob.n4pnt.gogbd.9ev8f.o7pqi.kkkdl.tncpi.nt0b9
```

I also redid the `|sync` stuff with no appreciable difference. Am I best served waiting on the next breach?

**Comment by joemfb** [comment]
Closing, as the only still-actionable item here is better communication of clay hashes, and we're doing that now.
