### ISSUE TITLE
Issues with replaying ships

### ISSUE THREAD

**Issue by lukebuehler** [urbit/urbit#5551]
I have several ships that had the checkpoint corrupted and I'm struggling tremendously with replaying them from the log.

I think a lot of the problems come from the memory requirements to do a full replay; the replays bail out before they succeed somewhere in the middle. However, the error I get is not very helpful, it usually looks something like this:

```
/sys/vane/ames/hoon:<[2.356 15].[2.356 79]>
/sys/vane/ames/hoon:<[2.391 5].[2.460 7]>
/sys/vane/ames/hoon:<[2.394 5].[2.460 7]>
play: bail: %exit
play: %hear event on /a/ames failed
```

The ships that don't succeed do not even have that many events, usually 1-2 million. Does anyone have any ideas or advice how to get the replay to succeed? How much memory is required on average? Obviously, melding or packing does not help here because there is no checkpoint yet.

**Comment by belisarius222** [comment]
"bail: %exit" means deterministic Nock crash, so I don't think it's a memory problem.  I think we had a jet mismatch that was corrected in the binary -- I seem to recall that you have to replay partially with the old binary, then switch to the new one and replay from there.

@joemfb can probably give you a more complete and helpful answer.

**Comment by philipcmonk** [comment]
It's true that there was a jet mismatch that makes replaying old ships difficult, but if those ships were ever run under the most recent binaries (v1.8) then they should have a one-time checkpoint backup from when they first ran under v1.8.  It would be in pier/.urb/bhk.  You should try and restore those to the chk directory.

**Comment by lukebuehler** [comment]
That makes sense, then: those ships were never run successfully under v1.8. I will try to run on an older binary. Which version had the mismatch?

**Comment by lukebuehler** [comment]
Small update. v1.6 and v1.7 did not work either, besides v1.8, but the replay succeeded on v.1.5, past the point where it usually failed.

**Comment by lukebuehler** [comment]
Unfortunately, the replay still failed, but later. I replayed with v1.5 until the error message below.

@belisarius222, you said "I seem to recall that you have to replay partially with the old binary, then switch to the new one and replay from there." How would I do that? Because once it bails, there is no checkpoint. The next replay starts from the beginning again.

```
[%eyre-unknown-receive 5.787]
pier: (1715157): play bail: mug mismatch 5fdea225 e4aa5ef
pier: (1715158): play: bail

[%poke %hear]
bar-stack=~[~[//ames]]
call: failed
/sys/vane/ames/hoon:<[880 3].[909 20]>
/sys/vane/ames/hoon:<[882 3].[909 20]>
/sys/vane/ames/hoon:<[883 3].[909 20]>
/sys/vane/ames/hoon:<[885 3].[909 20]>
/sys/vane/ames/hoon:<[886 5].[907 7]>
/sys/vane/ames/hoon:<[889 5].[907 7]>
/sys/vane/ames/hoon:<[895 5].[907 7]>
/sys/vane/ames/hoon:<[897 14].[897 53]>
/sys/vane/ames/hoon:<[1.243 5].[1.243 43]>
/sys/vane/ames/hoon:<[1.249 5].[1.263 17]>
/sys/vane/ames/hoon:<[1.251 5].[1.263 17]>
/sys/vane/ames/hoon:<[1.254 5].[1.263 17]>
/sys/vane/ames/hoon:<[1.330 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.331 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.334 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.342 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.343 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.344 5].[1.379 62]>
[%ames-crash-on-packet-from ~sardys]
/sys/vane/ames/hoon:<[1.345 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.349 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.378 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.379 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.379 10].[1.379 62]>
/sys/vane/ames/hoon:<[1.931 7].[1.956 69]>
/sys/vane/ames/hoon:<[1.934 7].[1.956 69]>
/sys/vane/ames/hoon:<[1.936 7].[1.956 69]>
/sys/vane/ames/hoon:<[1.938 7].[1.956 69]>
/sys/vane/ames/hoon:<[1.950 7].[1.956 69]>
/sys/vane/ames/hoon:<[1.956 7].[1.956 69]>
/sys/vane/ames/hoon:<[2.103 7].[2.167 9]>
/sys/vane/ames/hoon:<[2.106 7].[2.167 9]>
/sys/vane/ames/hoon:<[2.109 7].[2.167 9]>
/sys/vane/ames/hoon:<[2.110 7].[2.167 9]>
/sys/vane/ames/hoon:<[2.110 47].[2.110 71]>
/sys/vane/ames/hoon:<[2.328 5].[2.335 7]>
/sys/vane/ames/hoon:<[2.330 5].[2.335 7]>
/sys/vane/ames/hoon:<[2.330 9].[2.330 29]>
/sys/vane/ames/hoon:<[2.340 5].[2.351 7]>
/sys/vane/ames/hoon:<[2.342 5].[2.351 7]>
/sys/vane/ames/hoon:<[2.346 9].[2.349 11]>
/sys/vane/ames/hoon:<[2.348 15].[2.348 79]>
/sys/vane/ames/hoon:<[2.383 5].[2.452 7]>
Assertion '_(u3a_is_atom(b))' failed in noun/retrieve.c:1032
                                                            home: bailing out
Assertion 'eve_d == 1ULL + sef_u->sen_d' failed in worker/serf.c:766
                                                                    home: bailing out
Aborted
```

**Comment by belisarius222** [comment]
I think you'd need to replay up until just before the failing event, take a snapshot there, and then try the next events with a different binary.  I've never done this myself, so it's just hearsay, but I'm pretty sure there is a way to do it.  @joemfb knows the relevant commands, and @ryjm might too.

**Comment by Fang-** [comment]
You can replay up to a specific event with `urbit -n 123000 your-pier`, where `123000` is the event number.

Normally, this would save a special snapshot in `pier/.urb/roc`, however that functionality seems broken on old (and maybe latest) binaries? So you'll want to manually `cp -r pier/.urb/chk pier/.urb/chk-123000` to back up in between steps, in case you need to step back.

**Comment by lukebuehler** [comment]
@Fang- , thanks for the help, but I still can't get this to work. I always get an out of loom error once it tries to create the snapshot. I tried various event numbers (-n). Any other ideas? I would just breach that particular ship, but I got a few that have this problem and I would love to solve it without a breach.

```
kiln: downloading OTA update from %kids on ~sardys
pier: (100): play: done
---------------- playback complete ----------------
pier: replay barrier reached, cramming
serf (100): saving rock
hash-cons arena:
  root: B/144
  atoms (5521):
    refs: KB/135.300
    data: MB/23.843.137
    dict: KB/227.392
  total: MB/24.205.829
  cells (3743658):
    refs: MB/114.057.740
    dict: MB/310.162.864
  total: MB/424.220.604
total: MB/448.426.577

address 0 out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:129
                                         home: bailing out
pier: serf unexpectedly shut down
```

**Comment by joemfb** [comment]
@lukebuehler sorry for the delayed response. Are you running `urbit-v1.8`? If not, you should upgrade the binaries and try again. (If you are, this is a new bug, and we'll want to track that down.

**Comment by lukebuehler** [comment]
No worries.

No, I'm not, because I need to replay with an older version to avoid the jet mismatch. I'm using v1.5. I do have all the version installed but only with v.1.5 I can get past that part where the replay crashes.

**Comment by joemfb** [comment]
@lukebuehler my apologies -- I forgot about that crash in `v1.5`, which was fixed in a subsequent release. That fix was backported to v1.5 for these replay cases, you can download those binaries from: https://github.com/urbit/urbit/issues/5304#issuecomment-974379285.

**Comment by lukebuehler** [comment]
Ah perfect, thanks. Will try it out right away!

**Comment by lukebuehler** [comment]
I got it to work with Joe’s v1.5 binary. Thank you!

I replayed in 500k increments until v1.5 failed and then switched to v1.8, which got me to the end.
