### ISSUE TITLE
We don't handle suspend from terminal too well

### ISSUE THREAD

**Issue by juped** [urbit/urbit#621]
_What_ to do is easy - catch SIGTSTP, get into a good state, send ourselves SIGSTOP, then redraw the prompt line (or whatever is relevant to resuming). It's the details that are tough. Any solutions must be vaguely portable, please!

**Comment by ohAitch** [comment]
Kind of addressed by #592, but doing the correct thing would be nice. Maybe will do the right thing in `cc-release`, or at least something to keep in mind for potential alternate event frontend developers.

**Comment by jtobin** [comment]
Closing as a hacky subjective appraisal indicates this appears to be handled reasonably well on 0.8.0.

**Comment by ohAitch** [comment]
Reasonably well = same behavior as when this was filed, namely SIGSTP doesn't actually leave a process you can subsequently SIGCONT?

**Comment by jtobin** [comment]
Yeah you still can't SIGCONT it.  You get:

```
[received keyboard stop signal, exiting]
pier: exit
```

But this seems to be handled "reasonably well," for some definition of reasonable (what to expect was not clear to me from the OP).

**Comment by ohAitch** [comment]
Could you elaborate on how

> catch SIGTSTP, get into a good state, send ourselves SIGSTOP, then redraw the prompt line

is ambiguous?

**Comment by jtobin** [comment]
I didn't say it was ambiguous -- I said it was not clear to me from the OP!

My attention was on the title; I glossed over the issue body itself, extracting little from it, since I don't know much about SIGTSTP or SIGSTOP.  I did perform a simple `kill -TSTP $PID` and `kill -CONT $PID` just to test what actually happened, though.

Important to note: I'm absolutely not opposed to this being on-file, but as I mentioned in another comment, the issue should probably be repackaged/represented if anyone still deems it to be worthwhile.  Otherwise it (demonstrably) risks a fellow like me glossing over it and closing it. 😄

**Comment by ohAitch** [comment]
I think I am justified here in requesting a standard of Fellows not closing issues without comprehending their descriptions! Like, I support enforcement of "all issues should be plainly readable" even
but would like to request a procedural amendment from "assume that all issues by default do not contain information about the present state of the system, and should thus be closed" to "request specific clarification, if the request goes unanswered _then_ close the issue for being unanimously uncomprehended".

By default, if an issue has seen no activity(and the functionality it references is not outright gone), a safe assumption is this means no further issue-relevant information has been encountered and thus the issue is accurate as stands.

**Comment by joemfb** [comment]
Reopening, as I'm increasingly convinced our current ctrl-z handler is a misfeature.

**Comment by zalberico** [comment]
Closing in favor of https://github.com/urbit/urbit/issues/6033 (which the same thing, just with my attempt to distill down what we want with a clear summary/title and links).
